version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_pass
      WORDPRESS_CONFIG_EXTRA: |
        /* Enable REST API */
        define('WP_DEBUG', false);
        define('WP_DEBUG_LOG', true);
    volumes:
      - wordpress_data:/var/www/html
      - ./:/var/www/html/wp-content/plugins/patchledger-agent
    depends_on:
      - db
    networks:
      - patchledger

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_pass
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - patchledger

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: wp_user
      PMA_PASSWORD: wp_pass
    depends_on:
      - db
    networks:
      - patchledger

volumes:
  wordpress_data:
  db_data:

networks:
  patchledger: